name: yumoyumo.com
favicon: null
layout_spectrum: 0.7013836975675076
typography_spectrum: 0.9178790196310729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfcfe'
    - '#ff0e1c'
    - '#000406'
    - '#71fc2e'
    - '#00c4e2'
  brandStrength: 0.5188251533545554
  lightness: 0.4705176337156445
  saturation: 0.3435677206143737
  rhythmicContrast: 0.5
purpose: []
